refactor: simplifying loop logic with NodeType
jjyr/sparse-merkle-tree pull request #17
Opened 2021-03-07 08:02 UTC by quake

2021-03-08 02:19 UTC, jjyr requested changes

2021-03-08 02:19 UTC, jjyr commented on src/tree.rs
> +                let branch_node = self.store.get_branch(&node)?.expect("stored branch node");
return this error instead of panick
https://github.com/jjyr/sparse-merkle-tree/blob/master/src/error.rs#L7

2021-03-08 02:19 UTC, jjyr commented on src/tree.rs
> +            _ => unreachable!("should be called on pair node only"),
IMO this is not a good style, we can return Option<_> and start panic/error at the caller.

2021-03-08 02:19 UTC, jjyr commented on src/tree.rs
> +            _ => unreachable!("should be called on single node only"),
Same as the **above** comment.

2021-03-08 02:23 UTC, jjyr commented
There is a potential attack: the user manipulates the SMT data, then crashes the program by calling the SMT operations, so I suggest we return errors instead of panic unless the internal logic causes the inconsistency.

2021-03-14 01:24 UTC, quake commented
updated according to review comment, please review again, thanks

2021-03-15 09:51 UTC, jjyr approved these changes

2021-03-15 09:51 UTC, merged