refactor smt update related code
jjyr/sparse-merkle-tree pull request #9
Opened 2021-02-27 09:31 UTC by quake

2021-02-27 14:13 UTC, jjyr commented on src/tree.rs
> -            if height < TREE_HEIGHT {
`core::u8::MAX` is 255, the original `TREE_HEIGHT` is 256. this change has broken the original code.

2021-02-28 00:26 UTC, quake commented on src/tree.rs
> -            if height < TREE_HEIGHT {
there is a `height == TREE_HEIGHT` checking in original code: https://github.com/jjyr/sparse-merkle-tree/blob/3731562d8b0a9af3cc9487f254bd64daa1d13cc2/src/tree.rs#L327

I think putting `height + 1` into the queue is an unnecessary operation when height is 255 because it will break the loop in the next iteration, so I removed this.

2021-02-28 02:57 UTC, jjyr commented on src/tree.rs
> -            if height < TREE_HEIGHT {
Ok, I see. Pls change the code to this style which I think is more intuitive.

``` rust
            if height == core::u8::MAX {
                if proof.is_empty() {
                    return Ok(parent);
                } else {
                    return Err(Error::CorruptedProof);
                }
            }
            tree_buf.insert((height + 1, parent_key), (leaf_index, parent));
```

2021-02-28 03:08 UTC, quake commented on src/tree.rs
> -            if height < TREE_HEIGHT {
updated, please review again, thanks

2021-02-28 03:13 UTC, jjyr requested changes

2021-02-28 03:13 UTC, jjyr commented on src/tree.rs
> +                        if height < core::u8::MAX {
``` rust
            if height == std::u8::MAX{
                // tree only contains one leaf
                if leaves_path[leaf_index].is_empty() {
                    leaves_path[leaf_index].push(core::u8::MAX);
                }
                break;
            }
```

2021-02-28 03:13 UTC, jjyr commented on src/tree.rs
> +            if height < core::u8::MAX {
And here

2021-03-01 11:39 UTC, quake commented
I will split this PR into small ones for easier review.

https://github.com/jjyr/sparse-merkle-tree/pull/10

2021-03-03 07:15 UTC, quake commented
close via https://github.com/jjyr/sparse-merkle-tree/pull/14

2021-03-03 07:16 UTC, closed without merging